// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqixrebsusdpxmlmuowa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxaXhyZWJzdXNkcHhtbG11b3dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NjA3NDYsImV4cCI6MjA2MzAzNjc0Nn0.I5NNfNdFceDWUd-dMeNpLqdkMGvEuWai9kT6iWzFnX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);